# Generated by Django 2.2.24 on 2021-10-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_ddate',
            new_name='published_date',
        ),
    ]
